name: chinese_cities
description: A pure Dart libraries include chinese cities base on http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2020.
version: 0.0.1
homepage: https://github.com/laiiihz/chinese_cities

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
